SET ECHO ON LINESIZE 200 PAGESIZE 50 FEEDBACK ON TRIMSPOOL ON
SPOOL C:\Users\GreyD\IdeaProjects\IMS\sql\ketqua\01_instance.log

PROMPT === 1. Trang thai ban dau (SYSDBA, CDB$ROOT)
SELECT instance_name, status, database_status, logins FROM v$instance;
SELECT con_id, name, open_mode, restricted FROM v$pdbs;

PROMPT === 2. SHUTDOWN IMMEDIATE
SHUTDOWN IMMEDIATE

PROMPT === 3. STARTUP NOMOUNT: chi khoi dong instance (SGA + tien trinh nen)
STARTUP NOMOUNT
SELECT instance_name, status FROM v$instance;

PROMPT === 4. MOUNT: doc control file
ALTER DATABASE MOUNT;
SELECT status FROM v$instance;
SELECT name, open_mode, log_mode FROM v$database;

PROMPT === 5. OPEN READ ONLY (ca CDB)
ALTER DATABASE OPEN READ ONLY;
SELECT name, open_mode FROM v$database;
SELECT name, open_mode FROM v$pdbs;

PROMPT === 6. SHUTDOWN IMMEDIATE roi STARTUP binh thuong (MOUNT -> OPEN READ WRITE)
SHUTDOWN IMMEDIATE
STARTUP
ALTER PLUGGABLE DATABASE ALL OPEN;
SELECT name, open_mode, log_mode FROM v$database;
SELECT name, open_mode, restricted FROM v$pdbs;

PROMPT === 7. PDB: CLOSE -> OPEN READ ONLY -> thu ghi du lieu (phai loi ORA-16000)
ALTER PLUGGABLE DATABASE FREEPDB1 CLOSE IMMEDIATE;
SELECT name, open_mode FROM v$pdbs;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN READ ONLY;
SELECT name, open_mode FROM v$pdbs;
ALTER SESSION SET CONTAINER=FREEPDB1;
UPDATE SUCO_APP.SU_CO SET MO_TA = MO_TA WHERE MA_SC = 1;
SELECT COUNT(*) AS SO_SU_CO_DOC_DUOC FROM SUCO_APP.SU_CO;
ALTER SESSION SET CONTAINER=CDB$ROOT;

PROMPT === 8. PDB: CLOSE -> OPEN READ WRITE (tro lai binh thuong)
ALTER PLUGGABLE DATABASE FREEPDB1 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE FREEPDB1 OPEN READ WRITE;
SELECT name, open_mode FROM v$pdbs;
ALTER SESSION SET CONTAINER=FREEPDB1;
UPDATE SUCO_APP.SU_CO SET MO_TA = MO_TA WHERE MA_SC = 1;
ROLLBACK;
ALTER SESSION SET CONTAINER=CDB$ROOT;
SPOOL OFF
EXIT
